version: 2
build:
    os: ubuntu-20.04
    tools:
        python: "3"
python:
    install:
        - requirements: docs/requirements.txt
submodules:
    include: all
    recursive: true
sphinx:
  fail_on_warning: true
